# MARKER_GENES:
#   T_NK_cells:
#     dnT:
#       - FXYD2
#       - AC004585.1
#       - PTPN3
#       - MIR4422HG
#     CD4+ T:
#       - CD4
#       - BACH2
#       - ITGB1
#       - KLRB1
#       - GZMA
#     gdT:
#       - TRDV2
#       - TRGV9
#     CD8+ T:
#       - CD8A
#       - CD8B
#       - CST7
#       - TRAV1-2
#       - NCR3
#       - SLC4A10
#     Treg:
#       - FOXP3
#       - RTKN2
#       - IL2RA
#       - CTLA4